### PR TITLE
Farkhondeh dev1

### PR DESCRIPTION
**Pull request by F-sh2019**
## Description

_1) What does this PR do? 2) List out what you did._
Alarm Component: Included Alarm page and alarm component
## Related Issue

_Provide a link to the related issue 

## Type of Changes

_Feature update/change/addition, bug fix, styling update, etc._

## Acceptance Criteria

_Include the checked-off acceptance criteria from the issue._

## Update Screenshots

_Provide screenshots of the view before and after the changes._

## Testing Instructions

_In a list format, tell us how to test this PR._

## Learnings (Optional)

_Document any things you learned or 'gotchas' you experienced._

### CODE REVIEW

**Comment by GinaCastromonte** [comment]
Screenshot 2024-12-04 at 2 15 57 PM
There are still some formatting issues/ merge conflicts blocking this PR

**Comment by F-sh2019** [comment]
updated prettier and pckage.json file

**Comment by F-sh2019** [comment]
Updated prettier and package.json file

**Review by GinaCastromonte — APPROVED** [review]

**Review by ValeriGuerrero — APPROVED** [review]
Looks good!

**Pull request merged**
