### PR TITLE
Error page

### PR DESCRIPTION
**Pull request by sarross88**
## Description

1- If user types in a URL that doesn't exist they are redirected to this Error page

### CODE REVIEW

**Comment by sarross88** [comment]
I ran "npm run lint -- --fix" and the error still popped up, any suggestions??

**Comment by sarross88** [comment]
Error found, didn't like my apostrophe in can't, just removed it and pushed the new code, should work now

**Review by GinaCastromonte — CHANGES_REQUESTED** [review]
Hey Sarah!  When I ran this branch, all I saw was a blank page and a config error in the console.   After investigating, I downgraded the version of ChakraUI and some other dependencies, which allowed the content to appear on the page. Since I’m not familiar with Vite + ChakraUI, I can’t confirm if this is the optimal solution.  Let me know if you need help.  
@devandres-tech 
Screenshot 2024-11-27 at 1 32 18 PM

**Comment by devandres-tech** [comment]
@GinaCastromonte @sarross88 To fix the blank page we have to pass a prop to the ChakraProvider component:


```
mport React from 'react';
import { ChakraProvider, defaultSystem } from '@chakra-ui/react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './global.css';

ReactDOM.createRoot(document.getElementById('root')).render(
    <React.StrictMode>
        <ChakraProvider value={defaultSystem}> // <---------- pass this value here
            <App />
        </ChakraProvider>
    </React.StrictMode>
);
```
```

**Comment by sarross88** [comment]
I added index.css and will new variables, deleted global.css, and changed the main.jsx file to the above recommended.

**Comment by sarross88** [comment]
Just updated with the last request

**Review by ValeriGuerrero — APPROVED** [review]

**Pull request closed without merging**
