### PR TITLE
set up pages and routes

### PR DESCRIPTION
**Pull request by sarross88**
## Description

_1) I set up the site pages and corresponding routes 

## Type of Changes

_FIle changes to assets  holds all of our images 
_File changes to main.jsx to see App2.jsx
-I created an App2 so I didn't mess with the existing code before its moved 
_All my code is dependent on global css approval to work

### CODE REVIEW

**Comment by devandres-tech** [comment]
@sarross88 It seems we have some formatting errors
cc @GinaCastromonte

**Comment by GinaCastromonte** [comment]
@sarross88 Try to fix the formatting errors and push your code again

**Comment by sarross88** [comment]
Hey I mentioned in the description I changed the css file and my stuff as App2 so I didn't mess with the other code that needs to be moved to work. Is that the issue or do you see something else? If so can you be more specific?? Thanks!

**Comment by sarross88** [comment]
I ran "npm run format" and pushed the updated code

**Comment by sarross88** [comment]
I also changed back the main.jsx back to App.jsx and index.css as to not mess with others code

**Comment by devandres-tech** [comment]
@sarross88 @GinaCastromonte Maybe we can abandon this PR as the LoginAndRegisterPages PR already includes the changes in this PR. So in LoginAndRegisterPages branch we can test for both, login and register pages, as well as the routes included in this PR? Ideally we should try to keep our changes to a minimum and avoid committing lots of changes.

**Comment by sarross88** [comment]
Fixed the files, formatted and should be good now

**Pull request closed without merging**
