### PR TITLE
Login and register pages

### PR DESCRIPTION
**Pull request by sarross88**
## Description

1) Made component folder, added three files -index, Logo, and FormRow
2) Altered the Landing page to have the Logo component 
3) Made the login page 
3) Made the register page 
4) all are assoicated with App2.jsx hooked into the main.jsx currently 

## Related Issue

Not sure why I am getting some red errors, my local computer has no issues with the code.

### CODE REVIEW

**Comment by GinaCastromonte** [comment]
@sarross88 Try to fix the formatting issues and push your code again

**Comment by sarross88** [comment]
What is specifically wrong with the formatting?

**Comment by GinaCastromonte** [comment]
Screenshot 2024-11-25 at 12 06 32 PM

**Comment by GinaCastromonte** [comment]
I tested this branch, and I think the code from the "setup pages and routes" branch is already included here. Please confirm. Additionally, there should only be one App.jsx file that is integrated together. It seems the design is primarily for mobile views; however, the landing page appeared distorted on my laptop. Lastly, I noted that the images folder needs to be placed in either the assets or the public folder.  
Screenshot 2024-11-25 at 12 24 22 PM

**Comment by sarross88** [comment]
Fixed formatting and changed back main.jsx

**Comment by sarross88** [comment]
Just updated!

**Review by GinaCastromonte — APPROVED** [review]

**Review by ValeriGuerrero — APPROVED** [review]
Looks good

**Pull request merged**
