### PR TITLE
Style and structure

### PR DESCRIPTION
**Pull request by sarross88**
## Description

_1) Pulled the most recent 12-4-24 code from main, added styles and all my pages, made sure everything worked, added ChakraUI with no problems, npm install to make sure everything is up to date, I added an icon package!!!! 

## Testing Instructions

NPM INSTALL first!

### CODE REVIEW

**Comment by sarross88** [comment]
Can someone explain the check error, everything else works, is there a command I need to run??

**Comment by GinaCastromonte** [comment]
Screenshot 2024-12-02 at 9 29 36 PM
It's an apostrophe error

**Comment by GinaCastromonte** [comment]
Screenshot 2024-12-04 at 1 44 01 PM
It's an apostrophe error

**Comment by sarross88** [comment]
Just updated

**Pull request closed without merging**
